//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgisayarKontrol {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Ayarlar : global::System.Configuration.ApplicationSettingsBase {
        
        private static Ayarlar defaultInstance = ((Ayarlar)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Ayarlar())));
        
        public static Ayarlar Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Yardim {
            get {
                return ((double)(this["Yardim"]));
            }
            set {
                this["Yardim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UygulamaKapatilirkenSifreİstensinmi {
            get {
                return ((double)(this["UygulamaKapatilirkenSifreİstensinmi"]));
            }
            set {
                this["UygulamaKapatilirkenSifreİstensinmi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CmdEngellensinmi {
            get {
                return ((double)(this["CmdEngellensinmi"]));
            }
            set {
                this["CmdEngellensinmi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RunEngellensinmi {
            get {
                return ((double)(this["RunEngellensinmi"]));
            }
            set {
                this["RunEngellensinmi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GörevYöneticisiEngellensinmi {
            get {
                return ((double)(this["GörevYöneticisiEngellensinmi"]));
            }
            set {
                this["GörevYöneticisiEngellensinmi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("samet")]
        public string KullaniciAdi {
            get {
                return ((string)(this["KullaniciAdi"]));
            }
            set {
                this["KullaniciAdi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string KullaniciSifre {
            get {
                return ((string)(this["KullaniciSifre"]));
            }
            set {
                this["KullaniciSifre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KullaniciVarmi {
            get {
                return ((int)(this["KullaniciVarmi"]));
            }
            set {
                this["KullaniciVarmi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string YardimGösterilsinmi {
            get {
                return ((string)(this["YardimGösterilsinmi"]));
            }
            set {
                this["YardimGösterilsinmi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GizliCevap {
            get {
                return ((string)(this["GizliCevap"]));
            }
            set {
                this["GizliCevap"] = value;
            }
        }
    }
}
